# test-cross-tenant-deny-t2-to-t1.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-cross-deny
  namespace: vcl-t002-dev
  labels:
    fcp/control: "CTRL-NET-CROSS"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "20"              # order (verify can be 99)
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test
        image: curlimages/curl:8.4.0
        command: ["/bin/sh","-lc"]
        args:
        - |
          set -eu
          URL="http://echo.vcl-t001-dev.svc.cluster.local:80/"
          # try once; success (HTTP 200) means FAIL for isolation
          code=$(curl -sS -m 5 -o /dev/null -w '%{http_code}' "$URL" || true)
          if [ "$code" = "200" ]; then
            echo "CONTROL 1 (cross) FAILED — cross-tenant ALLOWED (HTTP 200)"
            exit 1
          else
            echo "CONTROL 1 (cross) PASSED — cross-tenant BLOCKED (HTTP=${code:-<no response>})"
            exit 0
          fi
