apiVersion: apps/v1
kind: Deployment
metadata:
  name: too-many-pods
  namespace: default
spec:
  replicas: 25            # > 20 pod quota
  selector:
    matchLabels:
      app: tiny
  template:
    metadata:
      labels:
        app: tiny
    spec:
      containers:
        - name: tiny
          image: busybox:1.36
          command: ["sh", "-c", "sleep 3600"]
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
