apiVersion: v1
kind: Pod
metadata:
  name: rq-memory-violator
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "50m"
          memory: "3Gi"      # > 2.5Gi quota → denied
        limits:
          cpu: "200m"
          memory: "3Gi"
