# test-sched-allow-t1.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: test-sched-allow
  namespace: test
  labels:
    fcp/control: "CTRL-SCHED-ALLOW"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-weight": "10"              # order (verify can be 99)
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
  
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      # Must land only on t001 nodes
      nodeSelector:
        tenancy.fcp.io/tenant: "t001"
      containers:
      - name: test
        image: busybox:1.36
        command: ["/bin/sh","-lc"]
        args:
        - |
          echo "CONTROL 3 (allow) PASSED — landed on $NODE_NAME"
          exit 0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
